server:
  port: 10074
  tomcat:
    threads:
      max: 20

management:
  server:
    port: 10075
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
