server:
  port: 10088
  tomcat:
    threads:
      max: 2

management:
  server:
    port: 10089
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
