server:
  port: 10086
  tomcat:
    threads:
      max: 2

management:
  server:
    port: 10087
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
